name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v26
      - name: Building package
        run: nix build
      - name: Copy binary to workspace
        run: |
          mkdir -p artifacts
          cp result/bin/rime artifacts/rime-linux-x86_64
      - name: Upload rime CLI binary
        uses: actions/upload-artifact@v4
        with:
          name: rime-cli-linux-x86_64
          path: artifacts/rime-linux-x86_64
          retention-days: 30 
